### ISSUE TITLE
Trouble Resolving References

### ISSUE THREAD

**Issue by ghost** [flipperbw/HSBuddy#3]
Still having trouble resolving several references -
Assembly-CSharp, Assembly-CShare-firstpass, Google.ProtocolBuffers,
Google.ProtocolBuffersLite, PcapDotNet.Core, and PcapDotNet.Packets.

I noticed that PcapDotNet looks to be a nuget package..? Attempting to pull it back down from NuGet isn't working to well for me. The rest, I'm not entirely sure.

Would it be possible to get them dropped into a reference assembly path and then referenced from there? That way I (and other contributors) can easily pick them up and work with the project.

Note - I'm working on a PC with Hearthstone installed and having these issues.

**Comment by flipperbw** [comment]
Odd - VS didn't sync the pcap files in the previous commit, but I've manually added them now.

Assembly\* and Google.\* are in the Hearthstone folder. Are you on x86 or 64? Currently, the reference is hardcoded at:

C:\Program Files (x86)\Hearthstone\Hearthstone_Data\Managed

Do those files exist for you there, or perhaps just in Program Files?

**Comment by ghost** [comment]
Cool, I'm picking up pcap now.

I'm on x64, but it appears the issue is that I installed Hearthstone to a different drive. :)

Those are located at the following location for me:
D:\Program Files (x86)\Hearthstone\Hearthstone_Data\Managed

I can understand always wanting to pull in the latest versions from the HS directory.. I'm not too worried about it. I'll just create the directory structure to match yours on my machine and copy the assemblies over.
